#!/bin/sh

cd gd
cmake . -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF \
	  -DCMAKE_C_FLAGS="-fPIC" -DVERBOSE=1 \
	  -DENABLE_PNG=1 -DENABLE_LIQ=0 -DENABLE_JPEG=0 -DENABLE_TIFF=0 \
	  -DENABLE_ICONV=1 -DENABLE_XPM=0 -DENABLE_WEBP=0 \
	  -DENABLE_FREETYPE=1 -DENABLE_FONTCONFIG=0 \
	  -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2
make gd_static
cd -
